hangman_words = [
    "abstract", "adventure", "alphabet", "ambition", "analogy", "analyze",
    "ancestor", "appetite", "approval", "argument", "artifact", "attitude",
    "audience", "authentic", "aviation", "balance", "baseball", "beautiful",
    "behavior", "birthday", "blossom", "boundary", "bracelet", "brilliant",
    "butterfly", "campaign", "capacity", "carnival", "category", "celebrate",
    "champion", "character", "chemical", "children", "chocolate", "cinnamon",
    "civilian", "classify", "climate", "colleague", "colorful", "comedian",
    "computer", "concrete", "confident", "confront", "conquer", "consider",
    "constant", "consumer", "continue", "contrast", "contribute", "courage",
    "creative", "criminal", "critical", "curiosity", "cylinder", "daughter",
    "decision", "definite", "delicate", "delivery", "describe", "designer",
    "determine", "develop", "diagonal", "diameter", "different", "difficult",
    "dilemma", "dimension", "direction", "disaster", "discover", "distance",
    "diversity", "division", "document", "domestic", "dominant", "dramatic",
    "education", "effective", "efficient", "elaborate", "elephant", "elevator",
    "emergency", "emotion", "emphasis", "employee", "engineer", "enormous",
    "entertain", "envelope", "equipment", "essential", "evaluate", "evidence",
    "excellent", "exchange", "exercise", "exhaust", "exhibition", "expansion",
    "expensive", "experience", "experiment", "explain", "explosion", "express",
    "extensive", "external", "fabulous", "familiar", "fantastic", "favorite",
    "festival", "flexible", "fountain", "fraction", "fragrant", "frequency",
    "friendly", "frontier", "function", "furniture", "galaxy", "generate",
    "generous", "genius", "genuine", "geometry", "glorious", "government",
    "graduate", "grateful", "gravity", "guarantee", "guidance", "happiness",
    "harmony", "harvest", "hazard", "healthy", "hearing", "heritage",
    "horizon", "humorous", "identity", "imagine", "impress", "improve"
]